name: keystone
version: ocata
summary: OpenStack Identity Service (keystone)
description: |
  Keystone provides authentication, authorization and service discovery
  mechanisms via HTTP primarily for use by projects in the OpenStack
  family. It is most commonly deployed as an HTTP interface to existing
  identity systems, such as LDAP.
confinement: classic
grade: devel

environment:
  PATH: $PATH:$SNAP/bin/:$SNAP/usr/sbin
  PYTHONPATH: $PYTHONPATH:$SNAP/lib/python2.7/site-packages

apps:
  uwsgi:
    command: snap-openstack keystone-uwsgi
    daemon: simple
  nginx:
    command: snap-openstack keystone-nginx
    daemon: forking
  manage:
    command: snap-openstack keystone-manage

parts:
  keystone:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/keystone/keystone-master.tar.gz
    python-packages:
      - pymysql
      - uwsgi
      - git+https://github.com/openstack/snap.openstack#egg=snap.openstack
    constraints: https://raw.githubusercontent.com/openstack/requirements/master/upper-constraints.txt
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
    stage-packages: [nginx]
    install:
      touch $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/paste/__init__.py
      touch $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/repoze/__init__.py
  templates:
    after: [keystone]
    plugin: dump
    source: snap
  config:
    after: [keystone]
    plugin: dump
    source: http://tarballs.openstack.org/keystone/keystone-master.tar.gz
    organize:
      etc/*.conf: etc/keystone/
      etc/*.ini: etc/keystone/
      etc/*.json: etc/keystone/
      etc/*.templates: etc/keystone/
    filesets:
      etc:
        - etc/keystone/*.conf
        - etc/keystone/*.ini
        - etc/keystone/*.json
        - etc/keystone/*.templates
    stage: [$etc]
    snap: [$etc]
