name: keystone
version: ocata
summary: OpenStack Identity Service (keystone)
description: |
  Keystone provides authentication, authorization and service discovery
  mechanisms via HTTP primarily for use by projects in the OpenStack
  family. It is most commonly deployed as an HTTP interface to existing
  identity systems, such as LDAP.
confinement: classic
grade: devel

environment:
  PATH: $PATH:$SNAP/bin/

apps:
  api:
    command: snap-openstack keystone-api
    daemon: simple
  manage:
    command: snap-openstack keystone-manage

parts:
  python:
    source: https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --enable-shared
      - --enable-unicode=ucs4
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
  keystone:
    after: [python]
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/keystone/keystone-master.tar.gz
    python-packages:
      - pymysql
      - uwsgi
      - git+https://github.com/openstack/snap.openstack#egg=snap.openstack
    constraints: https://raw.githubusercontent.com/openstack/requirements/master/upper-constraints.txt
    filesets:
      py27:
        - -usr/lib/python2.7/*
        - -usr/bin/2to3
        - -usr/bin/pydoc
        - -usr/bin/python2.7
    stage: [$py27]
    snap: [$py27]
  templates:
    after: [keystone]
    plugin: dump
    source: snap
  config:
    after: [keystone]
    plugin: dump
    source: http://tarballs.openstack.org/keystone/keystone-master.tar.gz
    organize:
      etc/*.conf: etc/keystone/
      etc/*.ini: etc/keystone/
      etc/*.json: etc/keystone/
      etc/*.templates: etc/keystone/
    filesets:
      etc:
        - etc/keystone/*.conf
        - etc/keystone/*.ini
        - etc/keystone/*.json
        - etc/keystone/*.templates
    stage: [$etc]
    snap: [$etc]
